### ISSUE TITLE
Format on commit produces different result

### ISSUE THREAD

**Issue by mlaggner** [krasa/EclipseCodeFormatter#219] opened 2021-01-02 10:11 UTC
looks like the issue from #178 re-appeared.

I've just updated all copyright headers from my .java files to 2021 and commited them with the option "Reformat code". Now I just opened 1 previously changed file and ran the eclipse code formatter and many lines changed (because I've also adopted the formatter profile a few days ago and I wanted to reformat _all_ files along with changing the copyright).

This could be either:

a) the old formatter xml has been cached somewhere (but why this is working when triggering the eclipse formatter via shortcut?)  
b) the commit dialog in IJ is not more calling the eclipse formatter

IJ community version 2020.3.1
Eclipse code formatter 20.7.201.6668.0

**Comment by krasa** [comment] 2021-01-02 11:19
The problem is probably that reformat while commiting reformats only VCS changed text - which afaik cannot be changed but I will take a look again later. 


Or it might be because the reformating is totally fucked in IntelliJ itself. If you also optimize imports, it will either stop commiting - https://youtrack.jetbrains.com/issue/IDEA-185735, so you have to press the commit button again, or it will silently not format - https://youtrack.jetbrains.com/issue/IDEA-255896. 
And if you format manually, it may also not do anything - https://youtrack.jetbrains.com/issue/IDEA-254749

You can enable debug for:  krasa.formatter
and you should see e.g.

```
2021-01-02 12:11:51,334 [ 878218]  DEBUG - ProxyCodeStyleManagerDelegator - invoking overriding {}({})reformatTextWithContext[PsiJavaFile:MainController.java, com.intellij.psi.codeStyle.ChangedRangesInfo@5d342a32] 
2021-01-02 12:11:51,335 [ 878219]  DEBUG - CodeStyleManager_IJ_2016_3plus - format MainController.java 24696 25071 
2021-01-02 12:11:51,335 [ 878219]  DEBUG - er.plugin.EclipseCodeFormatter - #format 24696-25071 
2021-01-02 12:11:51,335 [ 878219]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen MainController.java 
2021-01-02 12:11:51,336 [ 878220]  DEBUG - er.EclipseJavaFormatterAdapter - #formatInternal 
2021-01-02 12:11:51,336 [ 878220]  DEBUG - er.EclipseJavaFormatterAdapter - #starting to format by eclipse formatter 
2021-01-02 12:11:51,346 [ 878230]  DEBUG - er.EclipseJavaFormatterAdapter - reformatting done 
2021-01-02 12:11:51,348 [ 878232]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen done 
```

**Comment by mlaggner** [comment] 2021-01-02 12:20
thanks for the fast response - I will have an eye how this behaves in my project (btw: I have noticed that often I need to trigger the formatter twice before anything happens - this could be exactly the same behavior as described in the last two IJ issues)

**Comment by krasa** [comment] 2021-04-16 22:17
fixed in new IJ

**Closed by krasa** 2021-04-16 22:17 UTC
