### ISSUE TITLE
Update external libraries to Eclipse Mars 4.5

### ISSUE THREAD

**Issue by markiewb** [krasa/EclipseCodeFormatter#51] opened 2015-07-12 20:54 UTC
Eclipse Mars 4.5 has been released. Could you update the plugin to use the new jar files from the 4.5 distribution?!

**Comment by markiewb** [comment] 2015-07-12 20:56
I couldn't get the correct combination of jars to update it in my https://github.com/markiewb/eclipsecodeformatter_for_netbeans plugin.

**Comment by dkornishev** [comment] 2015-07-14 14:56
Sadly Mars code formatter is...different.  Will there be an option for using formatter from 4.5?

**Comment by krasa** [comment] 2015-07-14 21:34
What is the problem? The only thing different seems to be
that org.eclipse.jdt.internal.formatter.DefaultCodeFormatter needs a Map in
constructor, not Properties.​

**Comment by dkornishev** [comment] 2015-07-15 12:38
The problem is that code formatter in 4.5 actually formats differently than code formatter in 4.4.  See
http://eclipse-n-mati.blogspot.com/2015/06/eclipse-mars-how-to-switch-back-to.html for more details.

I don't know what the solution is (new version?  bundle both formatters and provide an option?).

**Comment by krasa** [comment] 2015-07-15 12:45
damn, I just pushed new libs :-)
 
We could bundle both versions and use a custom classloader to avoid conflicts.

**Comment by krasa** [comment] 2015-07-15 12:52
Actually we could bundle that old formatter eclipse plugin, that's easy.

**Comment by dkornishev** [comment] 2015-07-15 12:58
Will there be a new version of plugin soon, or will I need to build/install manually?

**Comment by krasa** [comment] 2015-07-15 13:18
Build manually. 

Not sure when I will have time to bundle that old formatter.

**Comment by dkornishev** [comment] 2015-07-15 13:25
I need the new formatter though...

**Comment by krasa** [comment] 2015-07-15 13:29
yep

**Comment by dkornishev** [comment] 2015-07-15 13:47
Instructions?  I imported the project but it doesn't even compile.  I ran dependency downloader pom and it looks like it fetched stuff but it didn't fix it

**Comment by krasa** [comment] 2015-07-15 14:29
you need to configure  IntelliJ SDK - https://www.jetbrains.com/idea/help/sdk.html - create new Intellij Platform SDK (just like with Java JDK, and select your installed IntelliJ)

all jars are commited, I just pushed fixed module config, so it should work out of box, otherwise just add those jars as libraries.

it should look like this:
![image](https://cloud.githubusercontent.com/assets/1160875/8700523/8769c17a-2b0c-11e5-8e48-e30a8c695164.png)

**Comment by krasa** [comment] 2015-07-18 13:53
@dkornishev you can download the builded plugin here:  https://github.com/krasa/EclipseCodeFormatter/releases/tag/15.1.132.637.0

I will release it in several days.

**Comment by krasa** [comment] 2015-07-20 16:33
#52 some of the new libs are compiled with JDK 1.7, I will need to make better OldFormatter jar which does not depend on them or something.

**Comment by krasa** [comment] 2015-07-22 07:19
So I have reverted several old jars from Eclipse 4.4 and used a custom classloader + some ugly reflection.

**Closed by krasa** 2015-07-22 07:19 UTC
